version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contafit_app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    environment:
      SERVICE_NAME: app
      APP_ENV: local
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: contafit_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: contafit_agenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
